""
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import SmoothScrollWrapper from "@/items/scrollsmoother";
import ConditionalNavbar from "@/items/conditionalNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="fixed top-0 left-0 z-50 w-full">
            <ConditionalNavbar />
          </div>
          {/* Smooth scroll content */}
          <SmoothScrollWrapper>
            {children}
          </SmoothScrollWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
